### PR TITLE
Fixes an error with Necromancer

### PR DESCRIPTION
**Pull request by agarian-2**

### CODE REVIEW

**Comment by nepphhh** [comment]
What exactly is the necro error and what does this fix?

**Comment by agarian-2** [comment]
EXTREMELY late response, but the following is the error:
`else if (my.shape === n.shape && n.settings.isNecromancer && my.type === 'food') bail = n.necro(my);
                                                                                                                                          ^
TypeError: n.necro is not a function`

The error would occur when you use the Necromancer (or Underseer), and try to collect squares. And well, this fixes the error.

**Comment by nepphhh** [comment]
Didn't all entities have an empty necro() function in the constructor? Why
would it throw that error?

**Comment by agarian-2** [comment]
You tell me, I've seen almost everybody complain about getting the error at least once in Discord (and I just realized that I forgot to remove the extra spaces from behind the code -_-)

**Comment by agarian-2** [comment]
I ran some tests, and found that for one, that block should be inside the function, not outside (because it's partially why the error happens). Second, `this.calculator` seems to return as just 7 rather than `'necro'`  when either Necro-based tanks are used.

**Comment by agarian-2** [comment]
I'm going to close this pull request, and make a new one that fixes this without removing the check.

**Pull request closed without merging**
