### PR TITLE
💓☂️ Updated with Glitch

### PR DESCRIPTION
**Pull request by Faris90**

### CODE REVIEW

**Comment by Koleotank** [comment]
No.

**Comment by mse-k** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by mse-k** [comment]
DIE

**Comment by mse-k** [comment]
FUCKING DIE TO DEATH

**Comment by rodrigoasfr24022003** [comment]
Faris, you know that this can be used against you right?

**Comment by eris-webserv** [comment]
Hmmmmm 🤔

**Comment by Faris90** [comment]
pathetic, look what bitches u all are

**Comment by rodrigoasfr24022003** [comment]
Faris, no license = automatically copyrighted

**Comment by Faris90** [comment]
says the bitch

**Comment by CrazyPython** [comment]
Come to the discords https://discord.gg/7xCaDdH

**Comment by Koleotank** [comment]
Wait, isn't Removing GPL3 from any repository containing it Illegal? (Considering that it's a Viral license)

**Comment by Faris90** [comment]
The arras community: 
🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡

**Pull request closed without merging**
